name: Build and Push Docker Image

on:
  workflow_dispatch:        # allow manual trigger
  push:
    branches: [ main ]      # or whatever branch you want

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

      # Optional: run the container for a quick test
      - name: Run container (test)
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
